<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>65069e5b-77f9-4662-8c41-5e45dc813da6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://www.lotteria.vn/resize.php?w=287&amp;h=265&amp;src=data/201635/4a_858.png&amp;zc=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;middle&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;wrap-pro other-pro-wrap&quot;]/ul[@class=&quot;list-pro&quot;]/li[@class=&quot;item-1&quot;]/a[1]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
