<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ad5655bf-b7ea-458d-9e67-98097ed3391d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://www.lotteria.vn/resize.php?w=250&amp;h=250&amp;src=data/201423/bigstar_6281.png&amp;zc=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;middle&quot;)/div[@class=&quot;wrapper wrap-content&quot;]/div[@class=&quot;wrap-pro&quot;]/ul[@class=&quot;list-pro&quot;]/li[@class=&quot;item-01 item-0 first&quot;]/a[1]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
